### ISSUE TITLE
README.md - pics show different prefix.

### ISSUE THREAD

**Issue by WiseDevHelper** [plexidev/discord-guardian#2]
**Is your feature request related to a problem? Please describe.**
If you see the example pictures, the dev uses the `g.` prefix whereas the guide says `g!`.

**Describe the solution you'd like**
Pictures where the dev uses `g!` instead. Or else the guide could mention `g.`.

**Additional context**
This was only posted because it was confusing to me which prefix to use.

**Comment by lorencerri** [comment]
A disclaimer has been added
