### ISSUE TITLE
Better ReadMe Tutorial

### ISSUE THREAD

**Issue by TheIttim** [plexidev/discord-guardian#5]
**Is your feature request related to a problem? Please describe.**
I am tired of helping people in #general-support with issues that could be covered by making the readme a bit more basic.(ie adding npm i, & the process of the .env file).

**Describe the solution you'd like**
I would like the Readme to be updated with a more basic tutorial.

**Describe alternatives you've considered**
Uhh, alternatives? Lots of repetitive conversations in #general-support

**Additional context**
https://discordapp.com/channels/343572980351107077/455431567318319145/729936529614569544 You can just scroll from there.

**Comment by lorencerri** [comment]
I don’t see how to improve the instructions without repeating things

**Comment by lorencerri** [comment]
I’ve improved the tutorial a bit. If you believe it can be further improved, please send a pull request. Thanks!
